Repository 1024pix/pix-db-stats, pull requests merged in 2022-10, with the labels that each got.

#21 Suivre les requêtes SQL en cours
  .nvmrc
  config.js
  docs/overview.puml
  lib/application/run-task-running-queries.js
  lib/application/schedule-tasks.js
  lib/application/task-running-queries.js
  lib/infrastructure/database-stats-repository.js
  lib/infrastructure/scalingo-api.js
  package-lock.json
  package.json
  tests/integration/application/task-cache-hit_test.js
  tests/integration/application/task-running-queries_test.js
  tests/integration/infrastructure/database-stats-repository_test.js
  tests/integration/infrastructure/scalingo-api_test.js
  tests/test-helper.js
Labels: :rocket: Ready to Merge, team-captains

#23 :bug: Les statistiques de requêtes ne sont plus tracées
  lib/infrastructure/database-stats-repository.js
  tests/integration/infrastructure/database-stats-repository_test.js
Labels: Tech review OK, :rocket: Ready to Merge, team-captains

#25 [BUGFIX] Les requêtes en cours ne sont pas extraites périodiquement
  config.js
  lib/application/run-task-running-queries.js
  lib/application/schedule-tasks.js
  lib/application/task-running-queries.js
  package-lock.json
  package.json
  tests/integration/application/schedule-task_test.js
  tests/integration/application/task-running-queries_test.js
  tests/test-helper.js
Labels: Tech review needed, :rocket: Ready to Merge, team-captains

#19 Formater automatiquement le code
  .circleci/config.yml
  .eslintrc.yaml
  .prettierrc.json
  config.js
  lib/application/run-cache-hit.js
  lib/application/run-task-metrics.js
  lib/application/run-task-progress.js
  lib/application/run-task-response-time.js
  lib/application/run-task-running-queries.js
  lib/application/run-task-statements.js
  lib/application/schedule-tasks.js
  lib/application/task-cache-hit.js
  lib/application/task-metrics.js
  lib/application/task-progress.js
  lib/application/task-response-time.js
  lib/application/task-running-queries.js
  lib/application/task-statements.js
  lib/infrastructure/database-stats-repository.js
  lib/infrastructure/http-service.js
  lib/infrastructure/logger.js
  lib/infrastructure/scalingo-api.js
  package-lock.json
  package.json
  tests/integration/application/schedule-task_test.js
  tests/integration/application/task-cache-hit_test.js
  tests/integration/application/task-running-queries_test.js
  tests/integration/infrastructure/database-stats-repository_test.js
  tests/integration/infrastructure/scalingo-api_test.js
  tests/test-helper.js
Labels: Tech review OK, :rocket: Ready to Merge, team-captains

#18 Utiliser la version de node 16.14
  .circleci/config.yml
  .nvmrc
  docs/pull_request_template.md
  lib/application/schedule-tasks.js
  package-lock.json
  package.json
Labels: Tech review needed, team-captains

#28 [CLEANUP] Simplifie la config circleci
  .circleci/config.yml
Labels: Tech review OK, :rocket: Ready to Merge, team-captains

#27 [FEATURE] Renomme la tache running-queries en queries-metric
  config.js
  lib/application/run-task-queries-metric.js
  lib/application/schedule-tasks.js
  lib/application/task-queries-metric.js
  lib/infrastructure/database-stats-repository.js
  lib/infrastructure/scalingo-api.js
  package.json
  sample.env
  tests/integration/application/schedule-task_test.js
  tests/integration/application/task-queries-metric_test.js
  tests/integration/application/task-running-queries_test.js
  tests/integration/infrastructure/database-stats-repository_test.js
  tests/integration/infrastructure/scalingo-api_test.js
Labels: Tech review OK, :rocket: Ready to Merge, team-captains

#26 [BUGFIX] Le conteneur s'arrête si Scalingo renvoie une erreur
  lib/application/task-cache-hit.js
  lib/application/task-metrics.js
  lib/application/task-progress.js
  lib/application/task-queries-metric.js
  lib/application/task-response-time.js
  lib/application/task-statements.js
  lib/infrastructure/logger.js
  sample.env
  tests/integration/application/task-cache-hit_test.js
  tests/integration/application/task-metrics_test.js
  tests/integration/application/task-progress_test.js
  tests/integration/application/task-queries-metric_test.js
  tests/integration/application/task-response-time_test.js
  tests/integration/application/task-statements_test.js
Labels: :rocket: Ready to Merge, team-captains, hacktoberfest-accepted
